return {
  version = "1.1",
  luaversion = "5.1",
  tiledversion = "2018.06.01",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 15,
  height = 10,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 9,
  nextobjectid = 1302,
  properties = {},
  tilesets = {
    {
      name = "proto",
      firstgid = 1,
      filename = "proto.tsx",
      tilewidth = 40,
      tileheight = 40,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      terrains = {},
      tilecount = 34,
      tiles = {
        {
          id = 0,
          image = "proto/player.png",
          width = 40,
          height = 40
        },
        {
          id = 1,
          image = "proto/projectile.png",
          width = 40,
          height = 40
        },
        {
          id = 2,
          image = "proto/shot0.png",
          width = 40,
          height = 40
        },
        {
          id = 3,
          image = "proto/shot1.png",
          width = 40,
          height = 40
        },
        {
          id = 4,
          image = "proto/shot2.png",
          width = 40,
          height = 40
        },
        {
          id = 5,
          image = "proto/spawner.png",
          width = 40,
          height = 40
        },
        {
          id = 6,
          image = "proto/weapon.png",
          width = 40,
          height = 40
        },
        {
          id = 7,
          type = "easyInput",
          properties = {
            ["debugEn"] = false,
            ["doNorm"] = false,
            ["easyInput"] = "oneTouch",
            ["keyboardEn"] = true
          },
          image = "proto/actionMapHelper.png",
          width = 40,
          height = 40
        },
        {
          id = 8,
          image = "proto/ball.png",
          width = 40,
          height = 40
        },
        {
          id = 9,
          image = "proto/block.png",
          width = 40,
          height = 40
        },
        {
          id = 10,
          image = "proto/blockA.png",
          width = 40,
          height = 40
        },
        {
          id = 11,
          image = "proto/blockB.png",
          width = 40,
          height = 40
        },
        {
          id = 12,
          image = "proto/blockC.png",
          width = 40,
          height = 40
        },
        {
          id = 13,
          image = "proto/blockD.png",
          width = 40,
          height = 40
        },
        {
          id = 14,
          image = "proto/blockE.png",
          width = 40,
          height = 40
        },
        {
          id = 15,
          image = "proto/blockE0.png",
          width = 40,
          height = 40
        },
        {
          id = 16,
          image = "proto/blockE1.png",
          width = 40,
          height = 40
        },
        {
          id = 17,
          image = "proto/blockE2.png",
          width = 40,
          height = 40
        },
        {
          id = 18,
          image = "proto/blockE3.png",
          width = 40,
          height = 40
        },
        {
          id = 19,
          image = "proto/blockF.png",
          width = 40,
          height = 40
        },
        {
          id = 20,
          image = "proto/blockG.png",
          width = 40,
          height = 40
        },
        {
          id = 21,
          image = "proto/blockH.png",
          width = 40,
          height = 40
        },
        {
          id = 22,
          image = "proto/blockP0.png",
          width = 40,
          height = 40
        },
        {
          id = 23,
          image = "proto/blockP1.png",
          width = 40,
          height = 40
        },
        {
          id = 24,
          image = "proto/blockP2.png",
          width = 40,
          height = 40
        },
        {
          id = 25,
          image = "proto/blockP3.png",
          width = 40,
          height = 40
        },
        {
          id = 26,
          properties = {
            ["camera"] = "fixed"
          },
          image = "proto/camera.png",
          width = 40,
          height = 40
        },
        {
          id = 27,
          image = "proto/damageBlockGreen.png",
          width = 40,
          height = 40
        },
        {
          id = 28,
          image = "proto/damageBlockRed.png",
          width = 40,
          height = 40
        },
        {
          id = 29,
          image = "proto/damageBlockYellow.png",
          width = 40,
          height = 40
        },
        {
          id = 30,
          properties = {
            ["bodyType"] = "dynamic",
            ["hasBody"] = true,
            ["isEnemy"] = true
          },
          image = "proto/enemy.png",
          width = 40,
          height = 40
        },
        {
          id = 31,
          image = "proto/gamelogic.png",
          width = 40,
          height = 40
        },
        {
          id = 32,
          image = "proto/keyboard.png",
          width = 40,
          height = 40
        },
        {
          id = 33,
          image = "proto/null.png",
          width = 40,
          height = 40
        }
      }
    },
    {
      name = "dungeon",
      firstgid = 35,
      filename = "dungeon.tsx",
      tilewidth = 32,
      tileheight = 32,
      spacing = 0,
      margin = 0,
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      terrains = {},
      tilecount = 26,
      tiles = {
        {
          id = 0,
          image = "dungeon/dirt_e.png",
          width = 32,
          height = 32
        },
        {
          id = 1,
          image = "dungeon/dirt_full.png",
          width = 32,
          height = 32
        },
        {
          id = 2,
          image = "dungeon/dirt_n.png",
          width = 32,
          height = 32
        },
        {
          id = 3,
          image = "dungeon/dirt_ne.png",
          width = 32,
          height = 32
        },
        {
          id = 4,
          image = "dungeon/dirt_nw.png",
          width = 32,
          height = 32
        },
        {
          id = 5,
          image = "dungeon/dirt_s.png",
          width = 32,
          height = 32
        },
        {
          id = 6,
          image = "dungeon/dirt_se.png",
          width = 32,
          height = 32
        },
        {
          id = 7,
          image = "dungeon/dirt_sw.png",
          width = 32,
          height = 32
        },
        {
          id = 8,
          image = "dungeon/dirt_w.png",
          width = 32,
          height = 32
        },
        {
          id = 9,
          image = "dungeon/dirt0.png",
          width = 32,
          height = 32
        },
        {
          id = 10,
          properties = {
            ["enemy"] = true
          },
          image = "dungeon/enemy_blob_acid.png",
          width = 32,
          height = 32
        },
        {
          id = 11,
          properties = {
            ["enemy"] = true
          },
          image = "dungeon/enemy_dragon_golden.png",
          width = 32,
          height = 32
        },
        {
          id = 12,
          image = "dungeon/fountain1.png",
          width = 32,
          height = 32
        },
        {
          id = 13,
          image = "dungeon/player.png",
          width = 32,
          height = 32
        },
        {
          id = 14,
          image = "dungeon/shop.png",
          width = 32,
          height = 32
        },
        {
          id = 15,
          image = "dungeon/stairs_enter.png",
          width = 32,
          height = 32
        },
        {
          id = 16,
          image = "dungeon/stairs_exit.png",
          width = 32,
          height = 32
        },
        {
          id = 17,
          image = "dungeon/stairs_stone_enter.png",
          width = 32,
          height = 32
        },
        {
          id = 18,
          image = "dungeon/stairs_stone_exit.png",
          width = 32,
          height = 32
        },
        {
          id = 19,
          image = "dungeon/stone1.png",
          width = 32,
          height = 32
        },
        {
          id = 20,
          image = "dungeon/stone2.png",
          width = 32,
          height = 32
        },
        {
          id = 21,
          image = "dungeon/stone3.png",
          width = 32,
          height = 32
        },
        {
          id = 22,
          image = "dungeon/stone4.png",
          width = 32,
          height = 32
        },
        {
          id = 23,
          properties = {
            ["enemy"] = true
          },
          image = "dungeon/troll.png",
          width = 32,
          height = 32
        },
        {
          id = 24,
          image = "dungeon/water_murky1.png",
          width = 32,
          height = 32
        },
        {
          id = 25,
          image = "dungeon/water1.png",
          width = 32,
          height = 32
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      id = 7,
      name = "logic",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1042,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 64,
          width = 40,
          height = 40,
          rotation = 0,
          gid = 8,
          visible = true,
          properties = {
            ["debugEn"] = true,
            ["easyInput"] = "twoTouch"
          }
        }
      }
    },
    {
      type = "objectgroup",
      id = 8,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1060,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1063,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1065,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1071,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1073,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1074,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1076,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1080,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1081,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1083,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1092,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1093,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1094,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1095,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1111,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1112,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1143,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1164,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1191,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        },
        {
          id = 1214,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 1218,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 43,
          visible = true,
          properties = {}
        },
        {
          id = 1219,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 38,
          visible = true,
          properties = {}
        },
        {
          id = 1222,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1223,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 1224,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 39,
          visible = true,
          properties = {}
        },
        {
          id = 1225,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 42,
          visible = true,
          properties = {}
        },
        {
          id = 1226,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 43,
          visible = true,
          properties = {}
        },
        {
          id = 1229,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {}
        },
        {
          id = 1230,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {}
        },
        {
          id = 1231,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 37,
          visible = true,
          properties = {}
        },
        {
          id = 1232,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 1233,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 35,
          visible = true,
          properties = {}
        },
        {
          id = 1234,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1235,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1236,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1237,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1238,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 36,
          visible = true,
          properties = {}
        },
        {
          id = 1240,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 40,
          visible = true,
          properties = {}
        },
        {
          id = 1241,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 40,
          visible = true,
          properties = {}
        },
        {
          id = 1245,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 40,
          visible = true,
          properties = {}
        },
        {
          id = 1251,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1252,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1253,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1254,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1255,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1256,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1257,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1258,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1259,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1260,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1261,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1262,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1263,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1264,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1265,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 32,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1266,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1267,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1268,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1269,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1270,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1271,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1272,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1273,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1274,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1275,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 128,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1276,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 160,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1277,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 192,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1278,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 224,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1279,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1280,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 288,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1281,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 256,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1282,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1283,
          name = "",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1284,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1285,
          name = "",
          type = "",
          shape = "rectangle",
          x = 96,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1286,
          name = "",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1287,
          name = "",
          type = "",
          shape = "rectangle",
          x = 160,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1288,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1289,
          name = "",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1290,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1291,
          name = "",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1292,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1293,
          name = "",
          type = "",
          shape = "rectangle",
          x = 352,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1294,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1295,
          name = "",
          type = "",
          shape = "rectangle",
          x = 416,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1296,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 320,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 1300,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      id = 4,
      name = "content",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      draworder = "topdown",
      properties = {},
      objects = {
        {
          id = 1297,
          name = "",
          type = "",
          shape = "rectangle",
          x = 239.333,
          y = 102.667,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 48,
          visible = true,
          properties = {}
        },
        {
          id = 1298,
          name = "",
          type = "",
          shape = "rectangle",
          x = 64,
          y = 96,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 49,
          visible = true,
          properties = {}
        },
        {
          id = 1301,
          name = "",
          type = "",
          shape = "rectangle",
          x = 303.333,
          y = 79.3333,
          width = 32,
          height = 32,
          rotation = 0,
          gid = 47,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
