-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:434f85e0e09f80d988b94fd37be33e4b$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "pBoy.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 90 },
				textureRect = { x = 0, y = 0, width = 80, height = 90 },
				spriteSourceSize = { width = 80, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pGirl.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 90 },
				textureRect = { x = 80, y = 0, width = 80, height = 90 },
				spriteSourceSize = { width = 80, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pHeart.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 90 },
				textureRect = { x = 160, y = 0, width = 80, height = 90 },
				spriteSourceSize = { width = 80, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "pStar.png",
				spriteColorRect = { x = 0, y = 0, width = 80, height = 90 },
				textureRect = { x = 240, y = 0, width = 80, height = 90 },
				spriteSourceSize = { width = 80, height = 90 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

